SkillsFunctionalTests/dotnet/2.1/host/DeploymentTemplates/template-with-new-rg.json
SkillsFunctionalTests/dotnet/2.1/skill/DeploymentTemplates/template-with-new-rg.json
SkillsFunctionalTests/dotnet/3.1/host/DeploymentTemplates/template-with-new-rg.json
SkillsFunctionalTests/dotnet/3.1/skill/DeploymentTemplates/template-with-new-rg.json
SkillsFunctionalTests/dotnet/v3/skill/DeploymentTemplates/template-with-new-rg.json
SkillsFunctionalTests/javascript/v3/skill/deploymentTemplates/template-with-new-rg.json
SkillsFunctionalTests/python/host/deploymentTemplates/template-with-new-rg.json
SkillsFunctionalTests/python/skill/deploymentTemplates/template-with-new-rg.json
build/yaml/dotnetDeploySteps.yml
build/yaml/dotnetHost2DotnetV3Skill.yml
build/yaml/dotnetHost2JavascriptSkill.yml
build/yaml/dotnetHost2JavascriptV3Skill.yml
build/yaml/dotnetHost2PythonSkill.yml
build/yaml/dotnetHost2dotnetSkill.yml
build/yaml/dotnetV3DeploySteps.yml
build/yaml/javascriptDeploySteps.yml
build/yaml/javascriptHost2DotnetSkill.yml
build/yaml/javascriptHost2DotnetV3Skill.yml
build/yaml/javascriptHost2JavascriptV3Skill.yml
build/yaml/javascriptHost2PythonSkill.yml
build/yaml/pythonDeploySteps.yml
build/yaml/pythonHost2DotnetSkill.yml
build/yaml/pythonHost2DotnetV3Skill.yml
build/yaml/pythonHost2JavascriptSkill.yml
build/yaml/pythonHost2JavascriptV3Skill.yml
build/yaml/pythonHost2PythonSkill.yml

Fixes #122
Fix the issue with invalid templates by using inner scope variables and reverse the workaround from the PR# 117 and PR# 118.
- Reversed the main YAML to use the deploy template using a new resource group.
- Removed step to create a new resource group in all main YAML as it is already created using the deploy template with new resource group.
- Updated all the `template-with-new-rg.json` with the inner scope variable, declaration of the new variables in that scope, and used it.
Note: when referring to all main YAML we are excluding the one for JS host to JS skill and with all the `template-with-new-rg.json` we are excluding the ones for the JS bots as this changes were already added in the PR# 121.
All the pipelines were tested with these changes applied and were working …

Reverse workaround for invalid template errors and apply fix

---

SkillsFunctionalTests/README.md

Build badges are not updating due to the rename of branch 'master' to 'main'. This change fixes the broken links.

Rename master branch to main in build badges.

---

SkillsFunctionalTests/tests/SkillFunctionalTests/Bot/TestBotClient.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/Configuration/BotTestConfiguration.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/Configuration/EnvironmentBotTestConfiguration.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/Configuration/IBotTestConfiguration.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/OAuthSkillTest.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/SimpleHostBotToEchoSkillTest.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/SkillFunctionalTests.csproj

Fixes #36
This PR migrates the tests in [SkillFunctionalTests](https://github.com/microsoft/BotFramework-FunctionalTests/tree/main/SkillsFunctionalTests/tests) from MSTests to xUnit.
- Replaced MSTest packages with xUnit in the .csproj.
- Removed `[TestClass]` attributes.
- Replaced `[TestMethod]` with `[Fact]`.
- Changed `[TestCategory]` to `[Trait]`.
- Replaced `Assert.IsTrue` with `Assert.True`.
- Replaced `Assert.Inconclusive` with `throw new XUnitException` (_a similar change was made in [Facebook](https://github.com/microsoft/botbuilder-dotnet/blob/main/FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/FacebookChatTests.cs#L135) and [Webex](https://github.com/microsoft/botbuilder-dotnet/blob/main/FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/WebexClientTest.cs#L119) …

Migrate SkillFunctionalTests project to XUnit

---

build/yaml/dotnetHost2DotnetV3Skill.yml
build/yaml/dotnetHost2JavascriptSkill.yml
build/yaml/dotnetHost2JavascriptV3Skill.yml
build/yaml/dotnetHost2PythonSkill.yml
build/yaml/dotnetHost2dotnetSkill.yml
build/yaml/dotnetInstallPackagesSteps.yml
build/yaml/dotnetTagBotBuilderVersion.yml
build/yaml/dotnetV3TagBotBuilderVersion.yml
build/yaml/javascriptHost2DotnetSkill.yml
build/yaml/javascriptHost2DotnetV3Skill.yml
build/yaml/pythonHost2DotnetSkill.yml
build/yaml/pythonHost2DotnetV3Skill.yml

Addresses #127
This PR adds BotBuilder version tags for all **DotNet** and **DotNetV3** pipelines combinations separating them in **Host** and **Skill**. 
The following display pattern was used when BotBuilderPackageVersion (**stable**, **preview**, **custom version**) is specified:
- `BotBuilderVersion{Host|Skill}={Version}+{stable|preview}` 
- `BotBuilderVersion{Host|Skill}={Version}` 
> **e.g.** 
> BotBuilderVersionHost=4.11.0-daily.20200911.165431 (preview)
> BotBuilderVersionSkill=3.30.2 (stable)
> BotBuilderVersionHost=4.10.0
- Add `dotnetTagBotBuilderVersion.yml` template file for getting and setting tag versions for DotNet.
- Add `dotnetV3TagBotBuilderVersion.yml` template file for getting and setting tag versions for DotNetV3.
- Added previous templates references to all …

[#127] [DotNet] Add BotBuilder Host and Skill tag versions

---

build/yaml/pythonDeploySteps.yml
build/yaml/pythonTagBotBuilderVersion.yml

Addresses #127
This PR adds BotBuilder version tags for all **Python** pipelines combinations separating them in **Host** and **Skill**. 
The following display pattern was used when BotBuilderPackageVersion (**stable**, **preview**, **custom version**) is specified:
- `BotBuilderVersion{Host|Skill}={Version}+{stable|preview}` 
- `BotBuilderVersion{Host|Skill}={Version}`
> **e.g.** 
> BotBuilderVersionHost=4.10.1 (stable)
> BotBuilderVersionHost=4.11.0.20200909.dev164711 (preview)
> BotBuilderVersionHost=4.9.2
- Add `pythonTagBotBuilderVersion.yml` template file for getting and setting tag versions for Python.
- Added previous template reference in the `pythonDeploySteps.yml` file.
In the following image there is a sneak peek about the version tags.

[#127] [Python] Add BotBuilder Host and Skill tag versions

---

build/yaml/javascriptDeploySteps.yml
build/yaml/javascriptTagBotBuilderVersion.yml

Fixes #127
This PR adds BotBuilder version tags for all **Javascript** pipelines combinations separating them in **Host** and **Skill**. 
The following display pattern was used when BotBuilderPackageVersion (**stable**, **preview**, **custom version**) is specified:
- `BotBuilderVersion{Host|Skill}={Version}+{stable|preview}` 
- `BotBuilderVersion{Host|Skill}={Version}`
> **e.g.** 
> BotBuilderVersionHost=4.10.1 (stable)
> BotBuilderVersionHost=4.11.0.20200909.dev164711 (preview)
> BotBuilderVersionHost=4.9.2
- Add `javascriptTagBotBuilderVersion.yml` template file for getting and setting tag versions for JS.
- Added previous template reference in the `javascriptDeploySteps.yml` file.
- Remove duplicated logic from _Set BBVersion and Registry URL_ step in `javascriptDeploySteps.yml` file. …

[#127] [JS] Add BotBuilder Host and Skill tag versions

---

BotFramework-FunctionalTests.ruleset
Directory.Build.props
SkillsFunctionalTests/tests/SkillFunctionalTests.sln
SkillsFunctionalTests/tests/SkillFunctionalTests/Bot/DirectLineSession.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/Bot/DirectLineSessionInfo.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/Bot/DirectLineToken.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/Bot/TestBotClient.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/Configuration/BotTestConfiguration.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/OAuthSkillTest.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/SimpleHostBotToEchoSkillTest.cs
SkillsFunctionalTests/tests/SkillFunctionalTests/SkillFunctionalTests.csproj
TranscriptTestRunner/ClientType.cs
TranscriptTestRunner/TestClientFactory.cs
TranscriptTestRunner/TestClients/DirectLineTestClient.cs
TranscriptTestRunner/TestRunner.cs
TranscriptTestRunner/TestScript.cs
TranscriptTestRunner/TranscriptConverter.cs
TranscriptTestRunner/TranscriptTestRunner.csproj

This PR adds StyleCop and FxCop analyzers to the SkillsFunctionalTest solution.
Also, fixes all errors and most warnings raised (we left three warnings that would require a refactor of some existing methods).
- Added StyleCop and FxCop packages to the projects.
- Added ruleset with the same configuration that the one in [_BotBuilder-dotnet_](https://github.com/microsoft/botbuilder-dotnet/blob/main/BotBuilder-DotNet.ruleset) repo.
- Added _Directory.Build.props_ file to share the ruleset through the solution's projects.
- Fixed all StyleCop and FxCop errors and most warnings.
- Separate classes in their own files
- Reordered properties, fields and methods.
- Added ConfigureAwait(false) to all async calls.
- Added `using` clause to disposable members. 
- Added `StringComparison.Ordinal` to …

[Skills Everywhere] Add StyleCop and FxCop analyzers

---

SkillsFunctionalTests/tests/.editorconfig
SkillsFunctionalTests/tests/SkillFunctionalTests.sln
SkillsFunctionalTests/tests/SkillFunctionalTests/SkillFunctionalTests.csproj
TranscriptTestRunner/TestClientBase.cs
TranscriptTestRunner/TestClients/DirectLineTestClient.cs
TranscriptTestRunner/TestRunner.cs
TranscriptTestRunner/TranscriptTestRunner.csproj

- Updated SkillFunctionalTests.csproj to always copy anything under the SourceTranscripts folder so I don't forget to set the copy always property.
- Changed TranscriptTestRunner.csproj to target netstandard2.0 and set it to use the latest C# version to make it more compatible with other consumers.
- TestClientBase: Removed ValidateActivityAsync (this has been moved to the runner.
- TestClientBase: Added GetNextReplyAsync to be able to pop activities from the client's internal queue.
- DirectLineTestClient: made it disposabled and implemented the dispose pattern to ensure we dispose direct line client.
- DirectLineTestClient: Implemented GetNextReplyAsync that stores whatever it pulls from DL in an internal queue and returns the first activity if any.
- DirectLineTestClient: added …

Refactor some classes and optimizations

---

Libraries/TranscriptTestRunner/TestRunner.cs
Tests/SkillFunctionalTests/SimpleHostBotToEchoSkillTest.cs
Tests/SkillFunctionalTests/SkillFunctionalTests.csproj

This PR implements ILogger interface replacing the `Debug.WriteLine` logger option by creating it from the LoggerFactory, it adds support for logging in Debug (Locally) and Console (Pipeline).
- Added new `ILogger` parameter to be passed onto the `TestRunner`.
- Added `LoggerFactory` on `SimpleHostBotToEchoSkillTest` to create the `ILogger` and send it to the `TestRunner`.
- Added to the `LoggerFactory`, Debug and Console support.
The following images shows the logging output, the first one is on the Debug output window on Visual Studio and the second one is the console output on the pipelines.

[Skills Everywhere] Add ILogger implementation

---

Libraries/TranscriptTestRunner/TestRunner.cs
Tests/SkillFunctionalTests/SimpleHostBotToEchoSkillTest.cs
Tests/SkillFunctionalTests/SkillFunctionalTests.csproj

In this PR:
- Made stopwatch in test runner a lazy property so it gets initialized when RunTestScript is called or when SendActivity is called (it was failing for non script based tests).
- Added a refence to [Divergic.Logging.Xunit](https://github.com/roryprimrose/Divergic.Logging.Xunit) so we can show the XUnit tests output in test explorer
- Modified SimpleHostBotToEchoSkillTest to add XUnitlogger and regrouped some tests to use [Theory] tests and avoid code duplication.
- Updated some nuget packages
- Modified some output strings
Details, with the XUnitLogger, we should see an "Open additional output for this result" link in VS Test explorer:
That should show the logger output:

Add XUnitLogger and some bug fixes

---

Libraries/TranscriptTestRunner/TestRunner.cs
Libraries/TranscriptTestRunner/TestScriptItem.cs
Libraries/TranscriptTestRunner/TranscriptTestRunner.csproj
Libraries/TranscriptTestRunner/XUnit/XUnitTestRunner.cs
Tests/SkillFunctionalTests/SimpleHostBotToEchoSkillTest.cs

This PR adds the XUnitTestRunner class that extends TestRunner to override the AssertReply method with XUnit asserts.
- Added **_XUnitTestRunner_** class.
- In TestRunner class, added the protected virtual **_AssertReply_** method with default assertions.
- Added xunit dependency to the project.
- Updated **_SimpleHostBotToEchoSkillTest_** tests to use the new class XUnitTestRunner.
Also:
- Added manual test in _SimpleHostBotToEchoSkillTest_
- Removed static _RunTestAsync_ method from TestRunner class.
- Renamed _TestScript_ class as _TestScriptItem_.
These images show what a failing test looks like with old and new implementations:

[Skills Everywhere] Add XUnitTestRunner class

---

Bots/DotNet/Skills/CodeFirst/EchoSkillBot-2.1/Bots/EchoBot.cs
Bots/DotNet/Skills/CodeFirst/EchoSkillBot-v3/Dialogs/RootDialog.cs
Bots/DotNet/Skills/CodeFirst/EchoSkillBot/Bots/EchoBot.cs
Bots/JavaScript/Consumers/CodeFirst/SimpleHostBot/hostBot.js
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot-v3/skill/index.js
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/bot.js
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/dialogs/mainDialog.js
Tests/SkillFunctionalTests/SimpleHostBotToEchoSkillTest.cs

This PR updates all bots messages to maintain parity with DotNet host and skill.
- Updates DotNet EchoSkillBot and EchoSkillBot-2.1 EchoBot ending message.
- Updates Javascript SimpleHostBot messages when "Say skill".
- Updates DotNet EchoSkillBot-v3 "Say end" and ending activity.
- Added JavaScript EchoSkillBot and EchoSkillBot-v3 `Ending conversation from the skill...` message when ending the conversation.
- Updated JavaScript EchoSkillBot confirm prompt to use _MessageFactory_ to have parity on _inputHint_ property.

[Skills Everywhere] Update Bot messages to maintain parity

---

Libraries/TranscriptTestRunner/TestClients/DirectLineTestClient.cs
Libraries/TranscriptTestRunner/TestRunner.cs
Libraries/TranscriptTestRunner/TestScriptItem.cs
Libraries/TranscriptTestRunner/TranscriptConverter.cs
Libraries/TranscriptTestRunner/TranscriptTestRunner.csproj
Libraries/TranscriptTestRunner/XUnit/XUnitTestRunner.cs
Libraries/TranscriptTestRunner/testscript.schema
Tests/SkillFunctionalTests/SimpleHostBotToEchoSkillTest.cs
Tests/SkillFunctionalTests/SkillFunctionalTests.csproj
Tests/SkillFunctionalTests/SourceTestScripts/HostReceivesEndOfConversation.json
Tests/SkillFunctionalTests/SourceTestScripts/ShouldRedirectToSkill.json

This PR improves the TranscriptConverter class by removing the undesired fields like ids and timestamps, and adding an assertion list to each _TestScriptItem_ of the TestScrip.
Also, fixes an issue where the _from.role_ and _recipient.role_ properties were not set on the bot's activity.
- **TranscriptConverter**:
- Added logic to remove the undesired fields (ids, timestamps and URLs).
- Created TestScriptItem's assertion list base on each bot activity properties.
- **DirectLineTestClient**: Set the _from.role_ and _recipient.role_ properties when pulling the bot's activities.
- **TestRunner**:
- Added validation to run the converter only when receiving a .transcript file.
- Used **_Adaptive Expressions_** for the assertions in _AssertActivityAsync_ method.
- **XUnitTestRunner**: Used …

[Skills Everywhere] Improve TranscriptConverter adding assertions list

---

build/yaml/dotnetHost2DotnetV3Skill.yml
build/yaml/dotnetHost2JavascriptSkill.yml
build/yaml/dotnetHost2JavascriptV3Skill.yml
build/yaml/dotnetHost2PythonSkill.yml
build/yaml/dotnetHost2dotnetSkill.yml
build/yaml/dotnetSetConfigFileSteps.yml
build/yaml/dotnetSetPaths.yml
build/yaml/dotnetTagBotBuilderVersion.yml
build/yaml/dotnetV3TagBotBuilderVersion.yml
build/yaml/javascriptHost2DotnetSkill.yml
build/yaml/javascriptHost2DotnetV3Skill.yml
build/yaml/javascriptHost2JavascriptSkill.yml
build/yaml/javascriptHost2JavascriptV3Skill.yml
build/yaml/javascriptHost2PythonSkill.yml
build/yaml/javascriptSetConfigFileSteps.yml
build/yaml/javascriptTagBotBuilderVersion.yml
build/yaml/pythonHost2DotnetSkill.yml
build/yaml/pythonHost2DotnetV3Skill.yml
build/yaml/pythonHost2JavascriptSkill.yml
build/yaml/pythonHost2JavascriptV3Skill.yml
build/yaml/pythonHost2PythonSkill.yml
build/yaml/pythonTagBotBuilderVersion.yml

This branch updates all Skill Functional Test YAML files to work with the directory refactor.
PowerShell steps were included to update DotNet's host and skill reference paths based on their version (2.1 or 3.1) since their refactored folder names were incompatible with the previous implementation.
- Updates all explicit path references in YAML files.
- Adds PowerShell scripts to update DotNet's bots paths.

[Skills Everywhere] Update YAML files with new structure

---

build/yaml/dotnetBuildSteps.yml
build/yaml/dotnetInstallPackagesSteps.yml
build/yaml/dotnetV3BuildSteps.yml

Nuget being used was 4.9.1. Now it's 5.8.0.
This fixes the many errors:
##[error]C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): Error NETSDK1005: Assets file 'D:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\obj\project.assets.json' doesn't have a target for 'netstandard2.0'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project.
Apparently brought on by a new version of msbuild being used.

Install later NuGet version for functional tests pipelines

---

Libraries/TranscriptTestRunner/Authentication/Session.cs
Libraries/TranscriptTestRunner/Authentication/SessionInfo.cs
Libraries/TranscriptTestRunner/Authentication/TestClientAuthentication.cs
Libraries/TranscriptTestRunner/Authentication/TokenInfo.cs
Libraries/TranscriptTestRunner/TestClientBase.cs
Libraries/TranscriptTestRunner/TestClients/DirectLineTestClient.cs

Fixes #176
This PR moves the `SignInAsync` and `GetSessionInfoAsync` methods functionalities out of the `DirectLineTestClient` class and renames the `DirectLineSession`, `DirectLineSessionInfo`, `DirectLineToken` classes.
- Added `TestClientAuthentication` static class with the namespace `TranscriptTestRunner.Authentication` containing the `SignInAsync` and `GetSessionInfoAsync` static methods.
- Moved and renamed the following classes to the `TranscriptTestRunner.Authentication` namespace:
- `DirectLineSession` => `Session`.
- `DirectLineSessionInfo` => `SessionInfo`.
- `DirectLineToken` => `Token`.
The following image shows the tests running and passing successfully.

[Skills Everywhere][#176] Move TestClient.SignIn method out of TestClient for reusability

---

Bots/DotNet/Consumers/Composer/SimpleComposerHostBot/language-generation/en-us/simplecomposerhostbot.en-us.lg
Bots/DotNet/Consumers/Composer/SimpleComposerHostBot/simplecomposerhostbot.dialog
Bots/DotNet/Skills/Composer/EchoComposerSkillBot/language-generation/en-us/echocomposerskillbot.en-us.lg

Fixes for #179
- Added inputHint to responses
- Added trigger to handle EoC from the skill for parity with SimpleHostBot.
- For now hardcoded the EoC code property so the test passes but created an [issue](https://github.com/microsoft/botbuilder-dotnet/issues/4999) in the SDK to have this fixed.

Fixed some lg issues for composer bots so the RunScripts test pass when running against composer

---

build/yaml/pythonDeployStepsExistingRG.yml
build/yaml/pythonDeployStepsNewRG.yml

Reverts the temporary changes of _azureSubscription_ in Python's resource creation step YAML files.
- Reverts `azureSubscription` to `$(AzureSubscription)` in `pythonDeployStepsExistingRG.yml` and `pythonDeployStepsNewRG.yml`

[Skills Functional Tests][Python] Revert YAML azureSubscription to $(AzureSubscription)

---

.gitignore
Bots/Python/Consumers/CodeFirst/SimpleHostBot/requirements.txt
Bots/Python/Skills/CodeFirst/EchoSkillBot/requirements.txt
Libraries/TranscriptTestRunner/TestClients/DirectLineTestClient.cs
Libraries/TranscriptTestRunner/TestRunner.cs
Libraries/TranscriptTestRunner/XUnit/XUnitTestRunner.cs

- Refactored DirectLineTestClient to defer retrieval of token until the conversation starts (and not in the constructor).
- Modified DirectLineTestClient.cs to discard the first activity sent to the bot if it is a ConversationUpdate (this is done implicitly by DL when a conversation starts)
- Modified DirectLineTestClient to use _conversation instead of  _tokenInfo to make thing consistent.
- Increased TestRunner polling to 250 ms
- Modified XUnitTestRunner to show expected activity in addition to the actual activity on failures.
- Added .vscode and .idea folders to gitignore file.
- Updated Python bots to reference 4.11.0

Misc fixes and refactorings for DL client and TestRunner

---

build/templates/template-bot-resources.json
build/yaml/deployBotResources/common/configureOAuth.yml
build/yaml/deployBotResources/common/createAppService.yml
build/yaml/deployBotResources/common/prepareResources.yml
build/yaml/deployBotResources/common/zipDeploy.yml
build/yaml/deployBotResources/deployBotResources.yml
build/yaml/deployBotResources/dotnet/deploy.yml
build/yaml/deployBotResources/dotnet/evaluateDependenciesVariables.yml
build/yaml/deployBotResources/dotnet/installDependencies.yml
build/yaml/deployBotResources/dotnet/installDependenciesV3.yml

Addresses #183
This PR adds the pipeline definition to deploy the bot resources needed for the Skills Functional Tests.
The pipeline has two sections, an initial stage to delete pre-existing resource groups and create new ones (one per language), and a batch of stages, one for each bot to be deployed.
This setup allows the user to handpick which bot to deploy or to use a pre-existing resource group through the stage selection panel before running a pipeline.
Deploys the following DotNet test bots:
- Simple Host Bot
- Simple Host Bot 2.1
- Echo Skill Bot
- Echo Skill Bot 2.1
- Echo Skill Bot v3
- Adds the  deployBotResources directory to host all related files
- Adds deployBotResources.yml file to define the pipeline and several YAML template files
- Adds the DotNet directory within …

[Skills Everywhere][#183] Add Deploy Bots pipeline

---

build/yaml/testScenarios/build.yml
build/yaml/testScenarios/runFunctionalTests.yml
build/yaml/testScenarios/runScenario.yml
build/yaml/testScenarios/runTestScenarios.yml

Addresses #183
This PR adds the yaml files for a pipeline that configure the bots and execute the test scenarios.
Each test scenario is a stage in the pipeline and they run sequentially.
- Added the following yaml files:
- `runTestScenarios.yml` : contains the list of test scenarios to execute.
- `runScenario.yml` : contains the steps to configure and execute the test scenario.
- `runfunctionalTest` : contains the steps to execute the tests.
- `build` : contains the steps to build the test project.
The following image shows the pipeline running successfully:
And this image shows the steps executed for each host-skill pair:

[Skills Everywhere][#183] Add Run Test Scenarios pipeline

---

build/yaml/deployBotResources/common/createDirectLine.yml
build/yaml/deployBotResources/dotnet/deploy.yml
build/yaml/deployBotResources/dotnet/deployComposer.yml
build/yaml/deployBotResources/js/deploy.yml
build/yaml/testScenarios/runFunctionalTests.yml

Fixes #214
This PR refactors the DirectLine creation task. The creation is extracted into a new template and called from the _deployBotResources_ pipeline.
The PR also updates the testScenarios pipeline to retrieve the DirectLine secret instead of creating it.
- Extracts the AzureCLI DirectLine creation task into `deployBotResources/common/createDirectLine.yml`
- Updates the following YAMLs to create the DirectLine channel when the bot is of type host:
-  `deployBotResources/dotnet/deploy.yml`
- `deployBotResources/dotnet/deployComposer.yml`
- `deployBotResources/js/deploy.yml`
- Updates `testScenarios/runFunctionalSteps.yml` to retrieve the DirectLine information and set the secret as an environment variable.
The following images shows successful pipeline executions for the changes …

[Skills Everywhere][#214] Move channel creation to bot deployment stage 

---

build/yaml/pythonDeployStepsExistingRG.yml

Fixes "Too many requests" issue in Python deployments. See the Test pipeline results [here](https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=204366&view=results).

Add botsku parameter to Python deploy steps with existing RG

---

Bots/JavaScript/.gitignore
Bots/JavaScript/Consumers/CodeFirst/SimpleHostBot/bots/hostBot.js
Bots/JavaScript/Consumers/CodeFirst/SimpleHostBot/package.json
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/package.json
Bots/Python/.gitignore
Bots/Python/Consumers/CodeFirst/SimpleHostBot/config.py
Tests/SkillFunctionalTests/Common/TestCaseBuilder.cs
Tests/SkillFunctionalTests/SingleTurn/EchoTests.cs

Fixes TBD
Added optional Func<TestCase, bool> parameter to TestCaseBuilder so the dev can inject a code block to evaluate if the TestCase needs to be excluded from the list of test cases.
Update EchoTests to use this parameter and exclude V3 skills for expect replies.

Add ShouldExclude parameter to TestCaseBuilder

---

README.md

Fixing a broken link to the Skill Functional Tests README

Fix: Broken link on README

---

Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Bots/SkillBot.cs
Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Controllers/ProactiveController.cs
Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Dialogs/ActivityRouterDialog.cs
Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Dialogs/Proactive/WaitForProactiveDialog.cs
Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Startup.cs
Tests/SkillFunctionalTests/ProactiveMessages/ProactiveTests.cs
Tests/SkillFunctionalTests/ProactiveMessages/TestScripts/ProactiveEnd.json
Tests/SkillFunctionalTests/ProactiveMessages/TestScripts/ProactiveEnd.transcript

Fixes #250
Modified proactive messages so the messages are sent only to the user that requested it rather than broadcasting messages to any user that has used the bot.
Updated related test.

Refactored ProactiveMessages

---

Tests/SkillFunctionalTests/SingleTurn/EchoComposerTests.cs

Fixes #254
This PR adds Composer SingleTurn scenario for testing Composer Consumer with Composer Skill only, until we add support to configure multiple skills in the Consumer.
- Added `EchoComposerTests.cs` file for testing Composer consumer with Composer skill.
In the following image there is a sneak peek for the test.

[Skills Everywhere] [#254] Add Echo Composer tests

---

Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/Dialogs/MainDialog.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/SkillsConfiguration.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/appsettings.json
Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Dialogs/ActivityRouterDialog.cs
Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Dialogs/Proactive/WaitForProactiveDialog.cs

Addresses #259 
This PR updates the **_WaterfallHostBot_** to support normal and expectReplies delivery modes, and multiple Echo Skill bots.
The bot now prompts the user to select the delivery mode and after selecting the type of skill (EchoSkill or WaterfllSkill), it shows the different target skills available for each type.
Also, a validation to avoid using ExpectReplies with V3 skill bots was added.
- Updated **_MainDialog_** class to include new prompts for Delivery Mode and target skills.
- Included a validation for ExpectReplies and V3 skill bots.
- Added all available echo skill bots with their configuration in **_appSettings.json_**.
- Updated _ActivityRouterDialog_ class of **_WaterfallSkillBot_** to pass the selected delivery mode to the echo skill.
These images show the new …

[Skills Everywhere] [#259] Update WaterfallHostBot to support expect replies and multiple skills

---

Tests/SkillFunctionalTests/CardActions/CardActionsTests.cs
Tests/SkillFunctionalTests/MessageWithAttachment/MessageWithAttachmentTests.cs
Tests/SkillFunctionalTests/ProactiveMessages/ProactiveTests.cs

Addresses #259
This PR updates all tests related to CardActions, ProactiveMessages and MessageWithAttachment to support the latest changes in WaterfallHostBot with expectReplies delivery mode and multiple skills.
- Updated `CardActions/CardActionsTests.cs`, `ProactiveMessages/ProactiveTests.cs` and `MessageWithAttachment/MessageWithAttachmentTests.cs` adding support for delivery mode expectReplies and multiple skills.
In the following image there is a sneak peek for the tests including normal and expect replies.

[Skills Everywhere][#259] Update Waterfall tests to support expect replies

---

build/yaml/dotnetBuildSteps.yml
build/yaml/dotnetHost2DotnetV3Skill.yml
build/yaml/dotnetHost2JavascriptSkill.yml
build/yaml/dotnetHost2JavascriptV3Skill.yml
build/yaml/dotnetHost2PythonSkill.yml
build/yaml/dotnetHost2dotnetSkill.yml
build/yaml/dotnetSetPaths.yml
build/yaml/functionalTestSteps.yml
build/yaml/javascriptHost2DotnetSkill.yml
build/yaml/javascriptHost2DotnetV3Skill.yml
build/yaml/javascriptHost2JavascriptSkill.yml
build/yaml/javascriptHost2JavascriptV3Skill.yml
build/yaml/javascriptHost2PythonSkill.yml
build/yaml/javascriptSetConfigFileSteps.yml
build/yaml/pythonHost2DotnetSkill.yml
build/yaml/pythonHost2DotnetV3Skill.yml
build/yaml/pythonHost2JavascriptSkill.yml
build/yaml/pythonHost2JavascriptV3Skill.yml
build/yaml/pythonHost2PythonSkill.yml
build/yaml/pythonSetConfigFileSteps.yml

Addresses #257
Updates the legacy pipeline definitions to support the most current version of the bots and test project, including new settings formats and `.sln` file cleanups.
**Note: This PR and PR #272  are related, both are required for legacy retro-compatibility.**
- Refactors the previously named `Get Bot Keys` step to set the bot keys into the test project's `appsettings.json` file using the new format.
- Updated `javascriptSetConfigFileSteps.yml` and `pythonSetConfigFileSteps.yml` to support new Consumer bot settings.
- Updated all DotNet `restore`, `build` and `package installation` processes to target _.csproj_ files instead of _.sln_ files. (Excluding DotNetV3).
The following screenshots show a set of pipelines representing all possible scenarios where updates took place.

[Skills Everywhere] [#257] Add support for legacy pipelines

---

Bots/DotNet/Skills/CodeFirst/EchoSkillBot-v3/EchoSkillBot-v3.csproj

Fixes #282
This PR adds $(SolutionDir) to the package references HintPath so the sln file can compile locally.
This PR also deletes a reference to Eric's publishing profile and DeploymentTemplates files (which have been centralized somewhere else)
My assumption is that $(SolutionDir) will be empty in the build pipeline and the build should work as it currently does, @ceciliaavila  @denscollo, can you check this PR doesn't break the EchoSkillBot-v3.csproj build?

Update the package references HintPath for EchoSkillBot-v3.csproj

---

Bots/DotNet/Skills/CodeFirst/EchoSkillBot-v3/EchoSkillBot-v3.csproj
build/yaml/deployBotResources/dotnet/deploy.yml
build/yaml/deployBotResources/dotnet/installDependenciesV3.yml
build/yaml/dotnetHost2DotnetV3Skill.yml
build/yaml/dotnetV3BuildSteps.yml
build/yaml/dotnetV3InstallPackagesSteps.yml
build/yaml/dotnetV3TagBotBuilderVersion.yml
build/yaml/javascriptHost2DotnetV3Skill.yml
build/yaml/pythonHost2DotnetV3Skill.yml

Addresses #282
This PR fixes issues for running legacy and new pipelines when restoring and building the EchoSkillBotDotNetV3 bot project.
- Added a new `SolutionDir` variable pointing out to the root bots' solution directory.
- Updated packages path references to the new `SolutionDir` folder.
In the following image there is a sneak peek for the pipelines.

[Skills Everywhere][#282] Fix EchoSkillBotDotNetV3 pipelines deployment

---

build/yaml/deployBotResources/dotnet/deployComposer.yml
build/yaml/deployBotResources/dotnet/installDependencies.yml

Adds dependencies source and version parameterization for Composer bots in the _Deploy Bot Resources_ pipeline.
Since Composer bots have runtimes made up of several projects the pipeline will update dependencies on a project by project basis.
**Note: If there are changes in the runtime dependenciess, the list of packages must be updated in the yamls as well.**
- Adds a dependencies variables evaluation step and one package installation step for each project with BotBuilder dependencies in the runtime in `dotnet\deployComposer.yml`
- Modifies `dotnet\installDependencies.yml` to add `preview`  to the package version for _Microsoft.Bot.Builder.Dialogs.Debugging_ and the step display name to output the project's name.
The following screenshot shows the updated pipeline working highlighting …

[Skills Everywhere] Add Composer package parameterization

---

Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/core/Microsoft.BotFramework.Composer.Core.csproj
Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/runtime/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/runtime/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/runtime/core/Microsoft.BotFramework.Composer.Core.csproj
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/runtime/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
Tests/SkillFunctionalTests/SingleTurn/EchoTests.cs
Tests/SkillFunctionalTests/SingleTurn/TestScripts/EchoMultiSkill.json
build/yaml/deployBotResources/dotnet/deployComposer.yml
build/yaml/deployBotResources/dotnet/installDependencies.yml

This PR also updates the composer projects to reference 4.12.0-daily.20210205.210249.a163e05 which is the build that includes the EoC fix (we should use one or higher going forward)
Fixes #278

Removes workaround for composer bots not sending EoC code.

---

Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/Dialogs/MainDialog.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/Dialogs/Sso/SsoDialog.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/Dialogs/Sso/SsoSignInDialog.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/Skills/EchoSkill.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/Skills/SkillDefinition.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/Skills/TeamsSkill.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/Skills/WaterfallSkill.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/SkillsConfiguration.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/TokenExchangeSkillHandler.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/appsettings.json
Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Dialogs/ActivityRouterDialog.cs

- Added Group property in SkillDefintion and updated appsettings.json with the property so we can render skill groups dynamically (there are still some assumptions on their names in SkillsConfiguration)
- Updated maindialog with new wording for skill groups, special case logic for SSO and to skip prompting for actions for skills that only have one action (echo).
- Removed explicity ListStyle for some choice prompts so this is handled by the SDK defaults.
- Refactored SkillDefintion and derived classes to use enums and make the code less repetitive.
- Renamed TeamsSsoConnectionName to SsoConnectionNameTeams (it sorts better)
- Updated SsoSignInDialog to display the connection name being used.
- Some renames in SsoDialog to align with the SDK naming

Interbranch: updates to the TeamsSkillBot branch

---

Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot/dialogs/activityRouterDialog.js
Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot/dialogs/delete/deleteDialog.js
Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot/dialogs/update/updateDialog.js

There's a PR pending in the C# repo that adds the update and delete scenarios to the Waterfall skill. I wanted to make sure those were replicated here for the port. You can see the host PR [here](https://github.com/microsoft/BotFramework-FunctionalTests/pull/315)

Adding Update and Delete scenarios to Waterfall skill

---

Bots/DotNet/nuget.config
build/yaml/FunctionalTestsBotsbuild.yml
build/yaml/SkillFunctionalTestsbuild.yml
build/yaml/functionaltests-CI,yml

This PR addresses an issue where [build/yaml/functionaltests-CI,yml](https://github.com/microsoft/BotFramework-FunctionalTests/blob/hates/build/yaml/functionaltests-CI,yml) fails to find the required packages to build the project.
[Composer Bots](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj#L20) are using the non-stable version `4.12.0-daily.20210205.210249.a163e05`, which can't be found in **Nuget.org**. 
To solve this, we updated the pipeline to install all dependencies and build the composer bots independently from the rest, following the same format as the [02 - Deploy Bot Resources pipeline](https://github.com/microsoft/BotFramework-FunctionalTe …

[FunctionalTests-CI] Fix issue: unable to find packages

---

build/yaml/dotnetInstallPackagesSteps.yml

This PR fixes the error found in the `Add custom Bot.Builder.Integration.AspNet.Core version` adding a task to install an older version of the NetCore SDK (5.0.103) as the failure happens with the latest version of the SDK (5.0.201) used in the pipeline's agent.
- Added **_UseDotNet_** task in [_dotnetInstallPackagesSteps.yml_](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/build/yaml/dotnetInstallPackagesSteps.yml) to install version 5.0.103.
These images show the pipeline running successfully with the new task added.

[Legacy Pipelines] Fix error in install packages step

---

build/yaml/dotnetBotsBuild-CI.yml
build/yaml/functionalTests-CI.yml
build/yaml/functionalTestsBuild-CI.yml

This PR fixes the errors in the dotnet build step replacing the _DotNetCoreCLI_ tasks with _NuGetCommand_ for the restore step and _MSBuild_ for building the solution.
- Updated **_dotnetBotsBuild-CI.yml_** to replace the restore and build tasks to build the entire solution with MSBuild.
- Updated _SolutionDir_ param in **_functionalTests-CI.yml_**. 
- Updated **_functionalTestsBuild-CI.yml_** to keep consistency using the same tasks to build the test project.
This image shows the pipeline running successfully after the changes.

[FunctionalTests-CI] Fix build error: Use MSBuild for build bots and test project

---

build/yaml/pythonBotsBuild-CI.yml

CI pipeline, failing at the install packages Python step caused by a warning introduced in the last pip version. downgrading to an earlier version of pip (pip==21.0.1) fixed the issues.
https://pip.pypa.io/en/stable/news/
https://stackoverflow.com/questions/67244301/warning-messages-when-i-update-pip-or-install-packages/67250419#67250419

##[error]WARNING: Value for scheme.headers does not match.

---

build/yaml/deployBotResources/deployBotResources.yml

This PR changes the default values of the DependencyVersion parameters to optional variables to be able to set them for scheduled runs.
- Updated `deployBotResources` yaml to set the parameters default values to variables.
These images show the bots deployed with the default versions except for Python Host that was set to 4.13.0

[Pipelines Support] Change dependency version parameters to use variables as default

---

Bots/JavaScript/Consumers/CodeFirst/SimpleHostBot/index.js
Bots/JavaScript/Consumers/CodeFirst/WaterfallHostBot/index.js
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/index.js
Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot/index.js

This PR adds configuration options to the JS bot's adapters to limit the total sockets.
We tested the changes in the pipelines with 20 runs we didn't see any ConnectionTimeout failure or the error message associated with it (connect ETIMEDOUT).

[Pipelines support] Apply fix for SNAT warnings in JS bots

---

build/yaml/testScenarios/configureConsumers.yml

This PR adds an extra validation to catch errors during the Test Project configuration. If one or more of the DirectLine secrets can't be found, the script will throw an error and abort the execution.
With this early catch, we'll prevent having _KeyNotFound_ errors in the tests.
- Updated `configureConsumers` to add retries for getting the DirectLine secrets from Azure and to throw an error in case it's blank after 3 attempts.
This image shows the error being thrown when the script can't set one of the bots' DirectLine secret.

[Pipelines Support] Add validation in configuration script to prevent KeyNotFound errors

---

Bots/DotNet/Consumers/CodeFirst/SimpleHostBot-2.1/SimpleHostBot-2.1.csproj
Bots/DotNet/Consumers/CodeFirst/SimpleHostBot/SimpleHostBot.csproj
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/WaterfallHostBot.csproj
Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/azurefunctions/Startup.cs
Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/core/Microsoft.BotFramework.Composer.Core.csproj
Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/runtime/tests/SkillConversationIdFactoryTests.cs
Bots/DotNet/Skills/CodeFirst/EchoSkillBot-2.1/EchoSkillBot-2.1.csproj
Bots/DotNet/Skills/CodeFirst/EchoSkillBot/EchoSkillBot.csproj
Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/WaterfallSkillBot.csproj
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/runtime/azurefunctions/Microsoft.BotFramework.Composer.Functions.csproj
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/runtime/azurefunctions/Startup.cs
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/runtime/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/runtime/core/Microsoft.BotFramework.Composer.Core.csproj
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/runtime/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/runtime/tests/SkillConversationIdFactoryTests.cs
Libraries/TranscriptConverter/TranscriptConverter.csproj
Libraries/TranscriptTestRunner/TranscriptTestRunner.csproj

Addresses #408
This PR updates the botbuilder packages of .NET bots and TestRunner project to the latest stable version (4.13.2).
Updated packages in the following bots:
- SimpleHostBotComposer
- SimpleHostBot-2.1
- SimpleHostBot
- WaterfallHostBot
- EchoSkillBotComposer
- EchoSkillBot-2.1
- EchoSkillBot
- WaterfallSkillBot
Solved ambiguous reference of `SkillConversationIdFactory` class in SimpleHostBotComposer and EchoSkillBotComposer.
Removed unnecessary using statements.
Updated packages in `TranscriptTestRunner` and `TranscriptConverter` projects.
These images show the bots working locally and being deployed successfully after the changes.

[Skills Everywhere][#408][.NET] Update bot and test projects to reference 4.13.x from nuget

---

build/yaml/testScenarios/configureConsumers.yml

After the pipeline updated the Azure CLI version to [2.24.0](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#may-25-2021), the configuration step of the _Run Test Scenarios_ pipeline started to fail.
This PR replaces the command [az resource wait --exists](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az_resource_wait) used to check the existence of the web apps with the command [az webapp show](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_show).
- Updated **_configureConsumers_** script to use `az webapp show` and check if the webapp is enabled before configuring the host and skills bots. 
These images show the configuration step before and after applying the …

[Test Scenarios pipeline] Fix error in configuration step

---

Tests/SkillFunctionalTests/SingleTurn/EchoTests.cs

Fixes #279
The latest composer runtime works fine with expectReplies, this PR removes the exclusion from the tests

Enabled composer expectreplies tests

---

Tests/SkillFunctionalTests/FileUpload/FileUploadTests.cs
Tests/SkillFunctionalTests/FileUpload/Media/TestFile.txt

Addresses #414
This PR fixes a concurrency issue in the FileUpload tests that was causing an exception in the pipelines when two tests ran for the same skill bot and tried to access the same file in the server.
- Updated [FileUploadTests](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/Tests/SkillFunctionalTests/FileUpload/FileUploadTests.cs) class to create and upload a different file for each test case adding a GUID to the file name.
- Deleted the [Media/TestFile.txt](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/Tests/SkillFunctionalTests/FileUpload/Media/TestFile.txt) file that was no longer needed.
This image shows the tests passing after the changes.

[#414] Fix SsoMiddleware error in FileUpload tests

---

build/templates/template-bot-resources.json
build/templates/template-python-bot-resources.json
build/templates/template-virtual-network-resources.json
build/yaml/deployBotResources/common/createAppService.yml
build/yaml/deployBotResources/deployBotResources.yml
build/yaml/deployBotResources/dotnet/deploy.yml
build/yaml/deployBotResources/dotnet/deployComposer.yml
build/yaml/deployBotResources/js/deploy.yml
build/yaml/deployBotResources/python/deploy.yml
build/yaml/sharedResources/createSharedResources.yml

Addresses #414 
**Note: For these changes to work, it's necessary to execute the new stage _Create Virtual Network_ of the [01-Create Shared Resources](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/build/yaml/sharedResources/createSharedResources.yml) pipeline.**
This PR adds an integration with the [Virtual Network](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/Microsoft.VirtualNetwork?tab=Overview) resource for the deployed app services using service endpoints in order to solve the SNAT port exhaustion issue that causes timeouts when running the Test Scenarios pipeline.
We came up with this solution due to an Azure proposal when going to "SNAT Port Exhaustion" within the Availability and Performance section of an Application Service. 
This proposal …

[#414][HTTP 500] Implement regional Virtual Network configuration to fix SNAT port exhaustion

---

Bots/DotNet/Consumers/CodeFirst/SimpleHostBot-2.1/Startup.cs
Bots/DotNet/Consumers/CodeFirst/SimpleHostBot/Startup.cs
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/Startup.cs

Updating C# botbuilder to 4.14.0-rc0 breaks the test bots with: 
`
error CS0104: 'AllowedSkillsClaimsValidator' is an ambiguous reference between 'Microsoft.BotFrameworkFunctionalTests.SimpleHostBot.Authentication.AllowedSkillsClaimsValidator' and 'Microsoft.Bot.Connector.Authentication.AllowedSkillsClaimsValidator' 
`

Disambiguate reference to AllowedSkillsClaimsValidator

---

build/templates/template-bot-resources.json
build/templates/template-python-bot-resources.json
build/yaml/deployBotResources/common/deleteResources.yml
build/yaml/deployBotResources/dotnet/deploy.yml
build/yaml/deployBotResources/js/deploy.yml

Fixes #438 
This PR fixes an issue where the `AzureWebApp@1` task fails with a Kudu Zip Deployment error (`Failed to deploy web package to App Service.`).
This issue was caused due to two set of configuration steps that made the App Service to restart and fail when processing the uploaded Zip:
1. There was missing the `WEBSITE_RUN_FROM_PACKAGE` setting from the ARM Template.
- When the variable is not set, the `AzureWebApp@1/runFromPackage` method will update the variable showing the `Updated App Service Application settings and Kudu Application settings` message, otherwise will show `App Service Application settings are already present.` avoiding the App Service restart.
2. Using `Microsoft.Web/sites/config` to configure the Virtual Network Subnet was causing the restart of the App …

[#438] Several deployments fail with "Run From Package Initialization failed."

---

Libraries/TranscriptTestRunner/TestClients/DirectLineTestClient.cs

Fixes #430
This PR adds a catch statement specifically for exceptions of type _AggregateException_. The issue is caused by an error on v2 of _xunit_ and _Divergix.Logging.Xunit_ NuGet packages. The error does not affect pipelines or tests, but it prints many stack traces in each run that may be source of confusion while debugging other issues.
After some research, we found an [issue](https://github.com/roryprimrose/Divergic.Logging.Xunit/issues/16) where it is mentioned that this is supposed to be fixed on v3 of these packages, but it is still on alpha, so we are temporary catching the exception and logging a warning instead.
Once a v3 stable version is available, the warning will be removed.
The following images show the before and after error message.

[#430][Test Scenarios Pipeline] System.AggregateException: An error occurred while writing to logger

---

build/yaml/sharedResources/createSharedResources.yml

Addresses #409
This PR updates the [01-Create Shared Resources](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/build/yaml/sharedResources/createSharedResources.yml) pipeline making the creation of the KeyVault and the AppRegistrations optional.
The **_KeyVaultObjectId_** variable is now optional and when it's set, the steps to create the keyVault and the AppRegistrations will be executed. If it's not set, or its value is 'empty', these steps will be skipped.
- Merged the `Create_Key_Vault` and `Create_App_Registrations` stages into one stage.
- Added a job to evaluate the value of the _KeyVaultObjectId_ variable.
- Added a condition to the `Deploy_Key_Vault` job to run only if the _KeyVaultObjectId_ is set.
These images show the pipeline running with and without the …

[#409] Update docs based on feedback - Make KeyVault creation optional

---

Docs/pipelines.md
build/yaml/deployBotResources/dotnet/deploy.yml
build/yaml/deployBotResources/dotnet/evaluateDependenciesVariables.yml
build/yaml/deployBotResources/js/evaluateDependenciesVariables.yml
build/yaml/deployBotResources/python/evaluateDependenciesVariables.yml

This PR fixes the behavior for the LATEST tag in the version dependency parameter for the deploy bot resources pipeline.
- Update  `evaluateDependenciesVariables.yml` for DotNet, JS, and Python to get the most recent version for all feeds when the `LATEST` option is entered in the corresponding version parameter.
- Update packages installed for DotNet v3 Bots, removing `Microsoft.Bot.Builder.Azure` since its versions are not updated and don't correspond with the rest of the packages, and added `Microsoft.Bot.Connector` which does have parity versions with the rest of the BotBuilder v3 packages.
- Update `evaluateDependenciesVariable.yml` for DotNet to include a message error when STABLE versions are asked for the Artifacts feed, since it doesn't contain stable versions.
- Update …

[DeployBotResources Pipeline] Update dependency version's LATEST tag

---

build/yaml/cleanupResources/cleanupResources.yml

Addresses #414
This PRs adds a `delete stage` for the Virtual Network to run over the `Cleanup Resources` pipeline.
Added a stage in the `cleanupResources.yml` file validating the vnet existence and deleting it if any.
Also, the `dependsOn` property for the `Delete_Resource_Group_Windows` stage was modified to only depends on the following stages:
-  Delete_Virtual_Network
-  Delete_App_Registrations
-  Delete_Key_Vault
-  Delete_App_Insights
-  Delete_CosmosDB
-  Delete_Container_Registry
This change was made to fix the stages visual arrangement within the pipeline view as you can see in the following image
The virtual network is being deleted successfully having an active connection or not

[#414] Add delete stage for Virtual Network

---

Libraries/TranscriptTestRunner/TestRunner.cs
Libraries/TranscriptTestRunner/XUnit/XUnitTestRunner.cs
Tests/SkillFunctionalTests/CardActions/CardActionsTests.cs
Tests/SkillFunctionalTests/FileUpload/FileUploadTests.cs
Tests/SkillFunctionalTests/MessageWithAttachment/MessageWithAttachmentTests.cs
Tests/SkillFunctionalTests/ProactiveMessages/ProactiveTests.cs
Tests/SkillFunctionalTests/ScriptTestBase.cs
Tests/SkillFunctionalTests/SignIn/SignInTests.cs
Tests/SkillFunctionalTests/SingleTurn/EchoTests.cs
Tests/SkillFunctionalTests/appsettings.json

Addresses #414
This PRs adds a _think time_ in the test runner before sending activities to the bot to give it time to properly save the state, reducing the occurrences of the _conversation restarted_ issue.
TestRunner.cs:
- Added ThinkTime variable set at creation with a default value of 0.
- Added a delay using the ThinkTime variable before sending the activity messages to the bot with the user role, using the value in milliseconds.
- Added log in the `RunTestAsync` method to include the ThinkTime and TestRequestTimeout values.
- Update the TimeRequestValue from seconds to milliseconds to have both variables consistent.
XUnitTestRunner.cs:
- Added ThinkTime variable to parse to the TestRunner.
Added ThinkTime variable in the `appsettings.json` to be used in the test client creation with …

[#414] Add think time in test runner to reduce conversation restarted errors

---

Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/.env

#minor
This PR fixes the issue with allowed callers in [EchoSkillBotJS](https://github.com/microsoft/BotFramework-FunctionalTests/tree/main/Bots/JavaScript/Skills/CodeFirst/EchoSkillBot).
- Updated the .env file adding `*` to the allowedCallers configuration.
This image shows the test pipeline working after the change.

Fix allowedCallers config for echoskillbotjs

---

Bots/DotNet/Consumers/CodeFirst/SimpleHostBot-2.1/SimpleHostBot-2.1.csproj
Bots/DotNet/Consumers/CodeFirst/SimpleHostBot/SimpleHostBot.csproj
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/WaterfallHostBot.csproj
Bots/DotNet/Skills/CodeFirst/EchoSkillBot-2.1/EchoSkillBot-2.1.csproj
Bots/DotNet/Skills/CodeFirst/EchoSkillBot/EchoSkillBot.csproj
Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/WaterfallSkillBot.csproj
Bots/JavaScript/Consumers/CodeFirst/SimpleHostBot/package.json
Bots/JavaScript/Consumers/CodeFirst/WaterfallHostBot/package.json
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/.env
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/authentication/allowedCallersClaimsValidator.js
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/bot.js
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/index.js
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/package.json
Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot/package.json
Bots/JavaScript/yarn.lock
Libraries/TranscriptConverter/TranscriptConverter.csproj
Libraries/TranscriptTestRunner/TranscriptTestRunner.csproj

#minor
This PR updates the BotBuilder versions in all bots to the latest 4.13.x available.
Also reverts the EchoSkillBot JS Cloud Adapter implementation to be compatible with the 4.13.6 version.
This way we get all the bots with the latest versions from R13 working.
Update all BotBuilder packages to the latest 4.13.x versions.
- 4.13.3 for DotNet bots
- 4.13.6 for JS bots
- Python bots don't require an update, the latest stable version is 4.13.0
Revert EchoSkillBot JS cloud adapter implementation.
Al all pipelines were run using the mentioned versions and the tests succeeded.

[R13] Update BotBuilder version to latest 4.13.x in all projects

---

Docs/README.md
Docs/pipelines.md
Docs/regionalVirtualNetworkIntegration.md
Docs/setupDockerContainer.md

Fixes #452
This PR adds new documents with information on the Virtual Network and how to set up a docker container integrated with the bots. Also updates existing readmes with the added variables for these integrations.
- Add `regionalVirtualNetworkIntegration.md`  document with information on the regional virtual network integration.
- Add `setupDockerContainer.md` document with steps to use a custom docker container with the bots.
- Update `README.md` with links to the new documents.
- Update `pipelines.md` adding the variables introduced with the VNet and containers integration.

[#452] Add VNet integration and docker container documentation

---

Bots/DotNet/Consumers/CodeFirst/SimpleHostBot-2.1/SimpleHostBot-2.1.csproj
Bots/DotNet/Consumers/CodeFirst/SimpleHostBot/SimpleHostBot.csproj
Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/WaterfallHostBot.csproj
Bots/DotNet/Consumers/Composer/SimpleHostBotComposer/SimpleHostBotComposer.csproj
Bots/DotNet/Skills/CodeFirst/EchoSkillBot-2.1/EchoSkillBot-2.1.csproj
Bots/DotNet/Skills/CodeFirst/EchoSkillBot/EchoSkillBot.csproj
Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/WaterfallSkillBot.csproj
Bots/DotNet/Skills/Composer/EchoSkillBotComposer/EchoSkillBotComposer.csproj
Bots/JavaScript/Consumers/CodeFirst/SimpleHostBot/package.json
Bots/JavaScript/Consumers/CodeFirst/WaterfallHostBot/package.json
Bots/JavaScript/Skills/CodeFirst/EchoSkillBot/package.json
Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot/package.json
Libraries/TranscriptConverter/TranscriptConverter.csproj
Libraries/TranscriptTestRunner/TranscriptTestRunner.csproj

Fixes #502
This PR updates the bots and test projects to BotBuilder 4.15.0.
- Updated the .Net and JS bots to use BotBuilder 4.15.0
- Updated _TranscriptTestRunner_ and _TranscriptConverter_ libraries to use BotBuilder 4.15.0
These images show the bots working locally and the pipelines running successfully.

[#502] Update Bots and Tests Project to 4.15.x

---

Bots/JavaScript/package.json

This PR excludes JS **_EchoSkillBot-v3_** from the build in the CI pipeline to avoid the error thrown by yarn after the upgrade of the NodeJS version in the [pipelines' virtual environment](https://github.com/actions/virtual-environments/releases/tag/win19%2F20211229.2).
This is a workaround until we review the yarn implementation and find a better solution.
- Excluded **_EchoSkillBot-v3_** project from yarn workspaces in the `Bots/JavaScript/package.json` file.
Here we can see the pipeline before and after applying the workaround.

[CI-Pipeline] Skip JS EchoSkillBot-v3 from CI pipeline

---

build/yaml/deployBotResources/dotnet/evaluateDependenciesVariables.yml

Fixes #516
This PR fixes an issue where the pipeline script in charge of gathering the `BotBuilder` version based on the `BotType, Registry and Version (Stable, Latest, Custom)` will obtain `5.x.x` versions instead of `4.x.x`.
Continue using the `nuget list` command by adding the `-AllVersions` flag will increase considerably the time it takes to gather all the versions of a package (`e.g. MyGet approx. 1 to 3 min`). Therefore, the fastest option was to use each registry API Rest (`e.g. MyGet approx. 1 to 3 sec`).
- Updated the `Evaluate source & version` task script to obtain `4.x.x` versions instead of `5.x.x`.
- Script refactored to use each registry API Rest instead of the `nuget list` command to reduce considerably the execution time.
- The structure has been cleaned up, improving …

[#516] Dotnet pipelines are pulling 5.x daily instead of 4.x

---

Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot/config.js
Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot/index.js

Fixes #528
This PR fixes an issue where the `ServerUrl` comes empty for Proactive, Audio, and MessageWithAttachments functionalities.
- Removed `configureServerUrl` method to configure the `ServerUrl` when accessed through the `/api/messages` endpoint in favor of just obtain the `WEBSITE_HOSTNAME` when deployed, otherwise `localhost`.
The following images show the error when the `ServerUrl` was empty and how it's working after the changes.

[#528] Fix WaterfallSkillJS ServerUrl not being assigned properly

---

build/yaml/testScenarios/runTestScenarios.yml

Addresses #517 
**_Note: The manually set [Build Completion Trigger](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers-classic?view=azure-devops#add-a-build-completion-trigger) should be removed as it's no longer recommended._**
These images show the _02.B_ pipeline successfully triggered after the _02.A_ finishes its execution, both in main and in one of the releases branches.

[#517] Issues running RC check against R15 branch - Pipeline Trigger

---

Bots/JavaScript/Skills/CodeFirst/EchoSkillBot-v3/package.json
Bots/JavaScript/yarn.lock

Fixes #525
> **Note:** Regarding Python's babel dependency, has been already addressed in the PR [botbuilder-python#1826](https://github.com/microsoft/botbuilder-python/pull/1826).
This PR updates the `chrono-node` version for the JavaScript `EchoSkillBot-v3` bot, by forcing the new `2.2.4` version and removing the `1.4.8` after the installation completes. Moreover, the `yarn.lock` has been updated to resolve to the new `2.2.4` version as well.
- Added the `chrono-node@2.2.4` dependency for the JavaScript `EchoSkillBot-v3` bot, and added the `postinstall` script to remove the `1.4.8` one after the installation finishes.
- Updated the `yarn.lock` file to resolve the `chrono-node@1.4.8` dependency to the new `2.2.4` version.
The following images show the Deploy and Test Scenarios pipelines …

[#525] Update components to latest versions

---

build/yaml/testScenarios/runTestScenarios.yml

[#517] Issues running RC check against R15 branch - Pipeline Trigger 4.15

---

build/yaml/testScenarios/runTestScenarios.yml

[#517] Issues running RC check against R15 branch - Pipeline Trigger 4.14

---

build/yaml/testScenarios/runTestScenarios.yml

[#517] Issues running RC check against R15 branch - Pipeline Trigger 4.13

---

build/yaml/testScenarios/runTestScenarios.yml

[#517] Issues running RC check against R15 branch - Pipeline Trigger 4.12

---

build/yaml/testScenarios/runTestScenarios.yml

[#517] Issues running RC check against R15 branch - Pipeline Trigger 4.11

---

build/yaml/testScenarios/runTestScenarios.yml

[#517] Issues running RC check against R15 branch - Pipeline Trigger 4.10

---

build/yaml/testScenarios/runTestScenarios.yml

[#517] Issues running RC check against R15 branch - Pipeline Trigger 4.9

---

build/yaml/deployBotResources/js/evaluateDependenciesVariables.yml

Fixes #517
When deploying the bots using the pipeline from the file [deploybotresources.yml](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/build/yaml/deployBotResources/deployBotResources.yml) using default values for version (null) and feed (npm) it gets the preview version instead of the latest stable version. 
The issue was located in the [evaluateDependenciesVariables.yml](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/build/yaml/deployBotResources/js/evaluateDependenciesVariables.yml) as the code was following a wrong path for this case and retrieving the version using the `next` tag instead of the `latest` tag.
- Added logic to check if the npm version is null or empty (the default case) and follow the behavior for the stable version.
- …

[#517] Issues running RC check against R15 branch - Get stable version from npm as default

---

Bots/DotNet/Skills/Composer/ComposerSkillBotDotNet/ComposerSkillBotDotNet/dialogs/FileUploadDialog/language-generation/en-us/FileUploadDialog.en-us.lg

#minor
This PR fixes the text in the FileUpload dialog of ComposerSkillBotDotNet to avoid the tests failing.
- Added a missing period in `FileUploadDialog.en-us.lg` to match the text with the rest of the bots.
These images show the FileUpload scenario with all its tests passing.

[#465] Create composer version of WaterfallSkillBotDotNet - Fix FileUpload dialog

---

build/yaml/deployBotResources/js/evaluateDependenciesVariables.yml

Addresses #517
When deploying the bots using the pipeline from the file [deploybotresources.yml](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/build/yaml/deployBotResources/deployBotResources.yml) using default values for version (null) and feed (npm) it gets the preview version instead of the latest stable version. 
The issue was located in the [evaluateDependenciesVariables.yml](https://github.com/microsoft/BotFramework-FunctionalTests/blob/main/build/yaml/deployBotResources/js/evaluateDependenciesVariables.yml) as the code was following a wrong path for this case and retrieving the version using the `next` tag instead of the `latest` tag.
- Added logic to check if the npm version is null or empty (the default case) and follow the behavior for the stable version.
- …

[#517][releases/4.15] Issues running RC check against R15 branch - Get stable version from npm as default

---

Bots/JavaScript/yarn.lock

Fixes #555
This PR updates the versions of the `cross-fetch`, `follow-redirects`, and `node-fetch` packages in the **_yarn.lock_** to recommended versions.
- Updated `follow-redirects` from version 1.14.5 to recommend 1.14.7.
- Updated `node-fetch` from version 2.6.6 to recommend 1.6.7.
- Updated `cross-fetch` from version 3.1.4 to 3.1.5 to be able to use the recommended version of `node-fetch`.
This image shows the bots working locally with the updated dependencies.

[#555] Update JS libraries

---

Bots/DotNet/ComposerSkillBotDotNet/Controllers/BotController.cs
Bots/DotNet/ComposerSkillBotDotNet/Controllers/SkillController.cs
Bots/DotNet/ComposerSkillBotDotNet/Program.cs
Bots/DotNet/ComposerSkillBotDotNet/Startup.cs
Bots/DotNet/EchoSkillBot-v3/ApiControllerActionInvokerWithErrorHandler.cs
Bots/DotNet/EchoSkillBot-v3/App_Start/WebApiConfig.cs
Bots/DotNet/EchoSkillBot-v3/Authentication/CustomAllowedCallersClaimsValidator.cs
Bots/DotNet/EchoSkillBot-v3/Authentication/CustomSkillAuthenticationConfiguration.cs
Bots/DotNet/EchoSkillBot-v3/Controllers/MessagesController.cs
Bots/DotNet/EchoSkillBot-v3/Dialogs/RootDialog.cs
Bots/DotNet/EchoSkillBot-v3/Global.asax
Bots/DotNet/EchoSkillBot-v3/Global.asax.cs
Bots/DotNet/EchoSkillBotComposer/Controllers/BotController.cs
Bots/DotNet/EchoSkillBotComposer/Controllers/SkillController.cs
Bots/DotNet/EchoSkillBotComposer/Program.cs
Bots/DotNet/EchoSkillBotComposer/Startup.cs
Bots/DotNet/SimpleHostBotComposer/Controllers/BotController.cs
Bots/DotNet/SimpleHostBotComposer/Controllers/SkillController.cs
Bots/DotNet/SimpleHostBotComposer/Program.cs
Bots/DotNet/SimpleHostBotComposer/Startup.cs

Addresses #554
This PR updates the namespaces in the bots' classes to be aligned with the Bot Framework namespaces.
- Updated namespaces in the classes of the following bots:
- ComposerSkillBotDotNet
- EchoSkillBot-v3
- EchoSkillBotComposer
- SimpleHostBotComposer
- Reordered using statements and removed the unnecessary ones.
These images show the pipelines running after the changes.

[#554] Update source code namespaces - Bots projects (2/3)

---

Bots/Python/EchoSkillBot/requirements.txt
Bots/Python/SimpleHostBot/requirements.txt
Bots/Python/WaterfallHostBot/requirements.txt
Bots/Python/WaterfallSkillBot/requirements.txt
Bots/Python/requirements.txt
build/yaml/deployBotResources/python/evaluateDependenciesVariables.yml

Addresses #503
This PR adds a `requirement.txt` file in `Bots/Python` folder to be referenced in each bot's _requirement.txt_ having the packages and their versions centralized in one place.
- Added a `requirement.txt` in `Bots/Python` with the packages and versions used by the bots.
- Updated each bot's `requirement.txt` to reference the one in the root folder.
- Updated the `evaluateDependenciesVariables` script to replace the reference in the bot's _requirement.txt_ with the content of the root file.
The following images show the pipelines passing using different combinations of version and feed.

[#503] Centralize BotBuilder version - Python

---

Bots/DotNet/ComposerSkillBotDotNet/dialogs/AuthDialog/AuthDialog.dialog
Bots/DotNet/ComposerSkillBotDotNet/dialogs/AuthDialog/language-generation/en-us/AuthDialog.en-us.lg
Tests/Functional/Skills/SignIn/SignInTests.cs

Addresses #503
This PR updates the ComposerSkillBotDotNet to handle the `tokens/response` event activity needed for the Auth test and enables the SignIn scenario for this bot.
- Added event handler in AuthDialog.dialog to set the token from the `tokens/response` event activity.
- Added missing `InputHint` and `Speak` properties in the bot's responses.
- Added _ComposerSkillBotDotNet_ in the list of `targetSkills` in the _SignInTests_ class.
This image shows the SignIn tests passing after enabling the _ComposerSkillBotDotNet._

[#503] Enable SignIn tests for ComposerSkillBotDotNet

---

Bots/JavaScript/Dockerfile
Bots/JavaScript/EchoSkillBot-v3/Dockerfile
Bots/Python/Dockerfile

#minor
This PR updates the `Dockerfile` endpoint to use [Microsoft Container Registry (MCR)](https://github.com/microsoft/containerregistry).
- Updated `Dockerfile` for JS, JSV3 and Python images from Docker to [Microsoft Container Registry (MCR)](https://github.com/microsoft/containerregistry).
- JS: `node:lts-buster` => `node:16`
- Python: `python:3.8-buster` => `python:3.10`
The following image shows the change and the working Test Scenarios pipeline.

Update Dockerfile endpoint to use Microsoft Container Registry (MCR)

---

Directory.Build.props
Tests.sln
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbAttribute.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbBaseFixture.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbBaseTests.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbPartitionedStorageFixture.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbPartitionedStorageTests.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbStorageFixture.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbStorageTests.cs
Tests/Integration/DotNet/Azure/Storage/Queues/AzureQueueBaseFixture.cs
Tests/Integration/DotNet/Azure/Storage/Queues/AzureQueueStorageTests.cs
Tests/Integration/DotNet/Azure/Storage/StorageBaseTests.cs
Tests/Integration/DotNet/Azure/Storage/StorageCase.cs
Tests/Integration/DotNet/Azure/Storage/StorageItem.cs
Tests/Integration/DotNet/ConfigurationFixture.cs
Tests/Integration/DotNet/Microsoft.Bot.Builder.Tests.Integration.csproj
Tests/Integration/DotNet/appsettings.json

Addresses #562
> **Note:** This PR depends on the commit 05e9916, which is already integrated into this branch.
This PR adds the `Azure Storage Queue` tests to the new `Integration` test project.
- Added `Microsoft.Bot.Builder.Dialogs.Adaptive` and `Microsoft.Bot.Builder.Azure.Queues` dependencies to the `Integration.csproj`.
- Added the `Storage` section with the `ConnectionString` to the `appsettings.json` file, which will be used to connect to the Emulator or Storage Account resource.
- Added the `AzureQueueBaseFixture.cs` file that will be in charge of corroborating if the Storage service is up and running, otherwise, the tests will fail.
- Added `AzureQueueStorageTests.cs` file with 5 new tests that execute the `QueueActivityAsync` method under different situations.
- Each test will …

[#562][DotNet] Add AzureStorageQueues tests to the test solution

---

Directory.Build.props
Tests.sln
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbAttribute.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbBaseFixture.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbBaseTests.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbPartitionedStorageFixture.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbPartitionedStorageTests.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbStorageFixture.cs
Tests/Integration/DotNet/Azure/Cosmos/CosmosDbStorageTests.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/AzureBlobStorageFixture.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/AzureBlobStorageTests.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/AzureBlobTranscriptStoreFixture.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/AzureBlobTranscriptStoreTests.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/BlobsAttribute.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/BlobsStorageBaseFixture.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/BlobsStorageFixture.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/BlobsStorageTests.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/BlobsTranscriptStoreBaseTests.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/BlobsTranscriptStoreFixture.cs
Tests/Integration/DotNet/Azure/Storage/Blobs/BlobsTranscriptStoreTests.cs
Tests/Integration/DotNet/Azure/Storage/StorageBaseTests.cs
Tests/Integration/DotNet/Azure/Storage/StorageCase.cs
Tests/Integration/DotNet/Azure/Storage/StorageItem.cs
Tests/Integration/DotNet/ConfigurationFixture.cs
Tests/Integration/DotNet/Microsoft.Bot.Builder.Tests.Integration.csproj
Tests/Integration/DotNet/appsettings.json

Addresses #562
> **Note:** This PR depends on the commit 05e9916, which is already integrated into this branch.
This PR adds the `Azure Storage Blobs` tests to the new `Integration` test project.
- Added `Microsoft.Bot.Builder.Azure.Blobs` dependency to the `Integration.csproj`.
- The base tests have been renamed and marked as `Fact`, so, when other classes inherit from it, it will inject automatically all the tests for a specific `Storage`.
- Added support for testing multiple `Storage` cases (e.g default config or with _TypeNameHandlingNone_ in the _JsonSerializer_).
- Added new `Blobs Storage` and `Azure Blob Storage` tests with similar tests and fixture configuration as for `CosmosDb`. Also, detects if the Blobs service is up and running.
- Added `AzureBlobTranscriptStoreFixture.cs` …

[#562][DotNet] Add Azure Storage Blobs tests to the test solution

---

Bots/Python/requirements.txt

Fixes #minor
The Python Waterfall Skill Bot Docker container fails to start with the error:
"301 Server Unavailable. docker container could not be started: bffnwaterfallskillbotpython-313043_0_34ae394b."
Docker log shows:
"ImportError: cannot import name 'UNICODE_EMOJI' from 'emoji' (/app/venv/lib/python3.10/site-packages/emoji/__init__.py)"
The container is deployed by pipeline "02.A. Deploy skill bots" without a reported error. 
The error bubbles up when "02.B. Run skill test scenarios (daily)" runs. It fails with:
"Error invoking the skill...(status is 503)." (Service unavailable)
emoji versions < 2.0.0 contain UNICODE_EMOJI, but >= 2.0.0 only contain UNICODE_DATA.
botbuilder-dialogs 4.14.0 depends on:
* recognizers-text 1.0.2a2.
* emoji 1.6.1
An external change in dependencies caused …

Fix Docker container failures for Python Waterfall Skill Bot deploy

---

build/yaml/common/getCosmosDbConnectionVariables.yml
build/yaml/deployBotResources/js/deploy.yml
build/yaml/deployBotResources/python/deploy.yml
build/yaml/testScenarios/configureConsumers.yml
build/yaml/testScenarios/functional.yml
build/yaml/testScenarios/test.yml

Fixes #minor
Fix AzureCLI@2: change failOnStderr to failOnStandardError. Documentation does not support the former syntax. (Former syntax is used in powershell and command line tasks, but not this one.) Hoping this will fix cases like the silent failure pushing the bffnsimplehostbotjs container to the container registry in 02.A. Deploy skill bots (daily)/314010. It had a "500 Internal Server Error", but the task remained green.
Shorten test timeouts from 60 to 20 minutes. The test jobs when succeeding take less than 7 minutes. When failing they can run out the clock.
Add "Show parameters" task to make troubleshooting easier.
This build exhibits the above tweaks: https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=314091&view=results

Skill bots functional test pipeline tweaks

---

Bots/DotNet/EchoSkillBot-3.1/Bots/EchoBot.cs
Bots/DotNet/EchoSkillBot-3.1/Controllers/BotController.cs
Bots/DotNet/EchoSkillBot-3.1/Microsoft.Bot.Builder.FunctionalTestsBots.EchoSkillBot31.csproj
Bots/DotNet/EchoSkillBot-3.1/Program.cs
Bots/DotNet/EchoSkillBot-3.1/Properties/launchSettings.json
Bots/DotNet/EchoSkillBot-3.1/SkillAdapterWithErrorHandler.cs
Bots/DotNet/EchoSkillBot-3.1/Startup.cs
Bots/DotNet/EchoSkillBot-3.1/appsettings.json
Bots/DotNet/EchoSkillBot-3.1/wwwroot/default.htm
Bots/DotNet/EchoSkillBot-3.1/wwwroot/manifests/echoskillbot-manifest-1.0.json
Bots/DotNet/Microsoft.Bot.Builder.FunctionalTestsBots.sln
Bots/DotNet/SimpleHostBot-3.1/AdapterWithErrorHandler.cs
Bots/DotNet/SimpleHostBot-3.1/Bots/HostBot.cs
Bots/DotNet/SimpleHostBot-3.1/Controllers/BotController.cs
Bots/DotNet/SimpleHostBot-3.1/Controllers/SkillController.cs
Bots/DotNet/SimpleHostBot-3.1/Dialogs/SetupDialog.cs
Bots/DotNet/SimpleHostBot-3.1/Microsoft.Bot.Builder.FunctionalTestsBots.SimpleHostBot31.csproj
Bots/DotNet/SimpleHostBot-3.1/Program.cs
Bots/DotNet/SimpleHostBot-3.1/Properties/launchSettings.json
Bots/DotNet/SimpleHostBot-3.1/SkillsConfiguration.cs
Bots/DotNet/SimpleHostBot-3.1/Startup.cs
Bots/DotNet/SimpleHostBot-3.1/appsettings.json
Bots/DotNet/SimpleHostBot-3.1/wwwroot/default.htm
Bots/JavaScript/SimpleHostBot/.env
Bots/Python/SimpleHostBot/.env
Bots/SimpleHostBotDotNet31.bot

Addresses #591
This PR adds the SimpleHostBotDotNet-3.1 and the EchoSkillBotDotNet-3.1 bots to the project.
- Added two new projects to the `Microsoft.Bot.Builder.FunctionalTestsBots` solution:
- Microsoft.Bot.Builder.FunctionalTestsBots.EchoSkillBot31
- Microsoft.Bot.Builder.FunctionalTestsBots.SimpleHostBot31
The following images show the new bots added working as expected.

[#591] Update dotnet bots to target net 6 - Add .NETCore3.1 bots
