microsoft/BotFramework-FunctionalTests

SkillsFunctionalTests/python/host/app.py
=> Update python host sample

SkillsFunctionalTests/tests/SkillFunctionalTests/Configuration/BotTestConfiguration.cs
Unifying alll argument exceptions.
=> Replace xUnitException

Libraries/TranscriptTestRunner/README.md, README.md, Tests/SkillFunctionalTests/README.md
This PR updates the repo documentation for the root repo's README, SkillsFunctionaTests README, and adds a new README file to the `TranscriptTestRunner` project.
- Added `TranscriptTestRunner` README file documentation.
- Updated Root README file to include reference to the `TranscriptTestRunner` project.
- Updated SkillsFunctionalTest README to add variables, update paths and reference the `TranscriptTestRunner` project.
=> [Skills Everywhere] Update Repository's documentation

build/yaml/dotnetHost2DotnetV3Skill.yml, build/yaml/dotnetHost2JavascriptSkill.yml, build/yaml/dotnetHost2JavascriptV3Skill.yml, build/yaml/dotnetHost2PythonSkill.yml, build/yaml/dotnetHost2dotnetSkill.yml, build/yaml/javascriptHost2DotnetSkill.yml, build/yaml/javascriptHost2DotnetV3Skill.yml, build/yaml/javascriptHost2JavascriptSkill.yml, build/yaml/javascriptHost2JavascriptV3Skill.yml, build/yaml/javascriptHost2PythonSkill.yml, build/yaml/pythonHost2DotnetSkill.yml, build/yaml/pythonHost2DotnetV3Skill.yml, build/yaml/pythonHost2JavascriptSkill.yml, build/yaml/pythonHost2JavascriptV3Skill.yml, build/yaml/pythonHost2PythonSkill.yml
This drops the build chaining-related tasks from pipelines. They have not been used for some time.
Also makes some dependency ("dependsOn") corrections.
=> Drop the unused build chaining tasks

Bots/DotNet/Consumers/CodeFirst/SimpleHostBot-2.1/SimpleHostBot-2.1.csproj, Bots/DotNet/Consumers/CodeFirst/SimpleHostBot/SimpleHostBot.csproj, Bots/DotNet/Consumers/CodeFirst/SsoRootBot/SsoHostBot.csproj, Bots/DotNet/Skills/CodeFirst/AttachmentsSkillBot/AttachmentsSkillBot.csproj, Bots/DotNet/Skills/CodeFirst/AuthSkillBot/AuthSkillBot.csproj, Bots/DotNet/Skills/CodeFirst/CardSkillBot/CardSkillBot.csproj, Bots/DotNet/Skills/CodeFirst/DialogSkillBot/DialogSkillBot.csproj, Bots/DotNet/Skills/CodeFirst/EchoSkillBot-2.1/EchoSkillBot-2.1.csproj, Bots/DotNet/Skills/CodeFirst/EchoSkillBot/EchoSkillBot.csproj, Bots/DotNet/Skills/CodeFirst/ProactiveSkillBot/ProactiveSkillBot.csproj, Bots/DotNet/Skills/CodeFirst/SsoSkillBot/SsoSkillBot.csproj, Bots/DotNet/Skills/CodeFirst/TeamsSkillBot/TeamsSkillBot.csproj, Bots/DotNet/Skills/CodeFirst/WeatherSkillBot/WeatherSkillBot.csproj
In this PR:
- Updated BF packages to 4.11
- Consolidated AdaptiveCards packages to 2..2
=> Updated packages 

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature-request.md
Added pre-labeled issue templates for bugs and feature-requests.
=> Added bug and feature-request issue templates.

build/yaml/pythonHost2JavascriptSkill.yml
Fix task Delete Resource Group. It was failing to delete.
=> Fix PyJsSkillBotFunctionalTest

build/yaml/deployBotResources/deployBotResources.yml
Addresses #183
This PR adds the Waterfall Host and Waterfall Skill bots to the bot deployment pipeline.
The following image shows a successful pipeline execution with the introduced changes:
=> [Skills Everywhere][#183] Add Waterfall Bots to Deploy pipeline

build/yaml/testScenarios/configureConsumers.yml
Update test pipeline's yaml to support new AppSetings structure.
=> [Skills Everywhere] Update test pipeline yaml

Bots/DotNet/Consumers/CodeFirst/WaterfallHostBot/Skills/WaterfallSkill.cs, Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Controllers/BotController.cs, Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Controllers/ProactiveController.cs, Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Controllers/SkillController.cs, Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Dialogs/ActivityRouterDialog.cs, Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/SkillConversationIdFactory.cs, Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Startup.cs, Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/appsettings.json
Adding the skill chaining to Waterfall scenario. The skill chaining currently calls the Echo skill.
=> Adding skill chaining scenario to waterfall

Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Dialogs/MessageWithAttachment/MessageWithAttachmentDialog.cs, Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/WaterfallSkillBot.csproj
For some reason this file didn't save in the last PR.
=> Updating path for 1 file

build/yaml/cleanupResources/cleanupResources.yml, build/yaml/cleanupResources/deleteAppRegistrations.yml, build/yaml/deployBotResources/common/configureOAuth.yml, build/yaml/deployBotResources/common/createAppService.yml, build/yaml/deployBotResources/common/createDirectLine.yml, build/yaml/deployBotResources/common/deleteResources.yml, build/yaml/deployBotResources/common/getAppRegistration.yml, build/yaml/deployBotResources/common/gitDeploy.yml, build/yaml/deployBotResources/common/zipDeploy.yml, build/yaml/deployBotResources/deployBotResources.yml, build/yaml/deployBotResources/dotnet/deploy.yml, build/yaml/deployBotResources/js/deploy.yml, build/yaml/deployBotResources/python/createAppService.yml, build/yaml/deployBotResources/python/deploy.yml, build/yaml/sharedResources/createAppRegistrations.yml, build/yaml/sharedResources/createSharedResources.yml, build/yaml/testScenarios/configureConsumers.yml, build/yaml/testScenarios/runTestScenarios.yml
Fixes #292
Extends Web App suffix support to all deployable resources. To do this, the suffix variables have been renamed to "ResourceSuffix" and applies to all resource names.
It also introduces minor improvements, such as declaring resource names at the start of each pipeline to apply suffixes once and naming consistency across all new pipelines.
The following optional variables have been renamed:
| Affected Pipelines | Old Name | New Name |
| - | - | - |
| All | **BotNames**Suffix | **Resource**Suffix |
| Deploy Bot Resources | DependeciesVersionHosts | Depende**n**ciesVersionHosts | 
| Deploy Bot Resources | DependeciesVersionSkills | Depende**n**ciesVersionSkills | 
| Deploy Bot Resources | DependeciesVersionSkillsV3 | Depende**n**ciesVersionSkillsV3 | 
- Extend suffix functionality …
=> [Skills Everywhere][#292] Add resource suffix support and minor improvements

Bots/DotNet/Skills/CodeFirst/EchoSkillBot-v3/packages.config
Rolling back changes suggested by dependabot.
=> Rolled back dependabot changes for dotnet V3 skill

Tests/SkillFunctionalTests/appsettings.json, build/yaml/deployBotResources/deployBotResources.yml
Renamed environment variables to use $(variableName) instead of $env:variableName.
=> Renames environment variables

build/templates/template-bot-resources-legacy-python-new.json, build/yaml/pythonDeployStepsNewRG.yml
This change will fix the Azure deployment failures for PyDotNetV3SkillBotFunctionalTest pipeline which is caused by the SKU of the App Service Plan Defaults to Standard values the region is running short on standard app service plan with Linux workers. So updating the region.
There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: 15943798-6430-4bac-b9de-426141a88aa7\"\r\n  }\r\n}"
=> Pythonissues

Bots/DotNet/FunctionalTestsBots.sln
=> Added EchoBot-V3 to the solution

Bots/DotNet/Skills/CodeFirst/EchoSkillBot-v3/EchoSkillBot-v3.csproj, Bots/DotNet/Skills/CodeFirst/EchoSkillBot-v3/Web.config, Bots/DotNet/Skills/CodeFirst/EchoSkillBot-v3/packages.config
Update OData and related packages to 5.8.4 based on dependabot suggestion.
=> Updates OData to 5.8.4

Tests/SkillFunctionalTests/README.md
Updated status badge URL in read me file.
=> Status badge fix

Libraries/TranscriptTestRunner/TestClients/DirectLineTestClient.cs
=> Added try catch with additional logging to DirectLineClient

build/yaml/common/deleteResourceGroup.yml, build/yaml/sharedResources/createAppRegistrations.yml, build/yaml/sharedResources/createSharedResources.yml
Addresses #377
This PR updates the yaml files of the `01 - Create Shared Resources` pipeline for:
- Replacing the use of global variables passing them as template parameters.
- Updating the use of quotes and indentation for consistency.
- Reordering the list of variables for clarity.
- `deleteResourceGroup`: fixed quotes and removed unnecessary ';' from the script.
- `createAppRegistrations`: fixed quotes and removed unnecessary ';' from the script.
-  `createSharedResources`: reordered the variables section and added descriptions. Fixed quotes and spacing.
=> [#377] Optimization: make parameters explicit in common yamls - Create Shared Resources

build/templates/template-bot-resources.json
=> Added  "WEBSITE_RUN_FROM_PACKAGE" setting for JS and dotnet Templates

build/templates/template-bot-resources.json, build/yaml/deployBotResources/dotnet/deploy.yml, build/yaml/deployBotResources/js/deploy.yml
Removed Run from package setting and configure yaml to use zipDeploy for dotnet and js
Addresses #438
=> Removed Run from package setting for dotnet and js zip deploys

build/yaml/deployBotResources/deployBotResources.yml, build/yaml/deployBotResources/dotnet/deployComposer.yml
Addresses #496
This PR updates the yamls in the R11 branch to be able to run the current implementation of the pipelines against it.
- Updated yamls and templates to match the current implementation of the pipelines.
These images show the pipelines running successfully against the R11 branch.
=> [Pipelines][#496] Adapt R11 branch to run Functional Tests pipelines

Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot/dialogs/proactive/waitForProactiveDialog.js, build/yaml/deployBotResources/deployBotResources.yml, build/yaml/testScenarios/configureConsumers.yml
Addresses #496
This PR updates the yamls in the R9 branch to be able to run the current implementation of the pipelines against it.
- Updated yamls and templates to match the current implementation of the pipelines.
- Removed Composer Host and Skill from Deploy and Test Scenarios pipelines due to not working with R9 packages.
These images show the pipelines running successfully against the R9 branch.
=> [Pipelines][#496] Adapt R9 branch to run Functional Tests pipelines

Bots/JavaScript/Skills/CodeFirst/WaterfallSkillBot/dialogs/proactive/waitForProactiveDialog.js, Tests/SkillFunctionalTests/SingleTurn/EchoTests.cs, build/yaml/deployBotResources/deployBotResources.yml, build/yaml/deployBotResources/dotnet/deployComposer.yml
Addresses #496
This PR updates the yamls in the R10 branch to be able to run the current implementation of the pipelines against it.
- Updated yamls and templates to match the current implementation of the pipelines.
- Added a case to the workaround for the EOC in Composer.
These images show the pipelines running successfully against the R10 branch.
=> [Pipelines][#496] Adapt R10 branch to run Functional Tests pipelines

build/yaml/testScenarios/functional.yml
#minor
This PR fixes the project's namespaces in the **_02.B Run skill test scenarios_** pipeline.
=> Fix project name in test pipeline

build/yaml/deployBotResources/deployBotResources.yml
=> Fix 02A-Deploy-Skill-Test-Bots-(daily) .yml comments

build/scripts/ConfigureConsumers.ps1, build/yaml/testScenarios/functional.yml, build/yaml/testScenarios/runTestScenarios.yml
Fix reference to pipeline 02A-Deploy-Skill-Test-Bots-(daily) which has been renamed.
Add test timeout.
Fix $SharedResourceSuffix parameter.
=> Fix pipeline reference in 02B-Run-Skill-Tests-(daily)
